import Head from "next/head";
import SignZRX from "@/components/SignZRX";
import GetZRX from "@/components/GetZRX";

export default function Home() {
  return (
    <>
      <Head>
        <title>0x dApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex flex-col space-y-4">
        <SignZRX />
        <hr />
        <GetZRX />
      </main>
    </>
  );
}
